# Generated by Django 3.0.6 on 2020-05-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200520_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='post_content',
            new_name='projects_content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='post_published',
            new_name='projects_published',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='post_title',
            new_name='projects_title',
        ),
    ]
