# Generated by Django 3.0.6 on 2020-05-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200520_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projects_content',
            new_name='project_content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projects_published',
            new_name='project_published',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projects_title',
            new_name='project_title',
        ),
    ]
