# Generated by Django 3.0.6 on 2020-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200521_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_author',
            field=models.CharField(default='No Author', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='No Image', upload_to=''),
        ),
    ]
