# Generated by Django 3.0.6 on 2020-05-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200523_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_published']},
        ),
    ]
