# Generated by Django 3.0.6 on 2020-05-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200516_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
