# Generated by Django 3.0.6 on 2020-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(max_length=50)),
                ('experience_summary', models.CharField(default='No summary', max_length=100)),
                ('experience_content', models.TextField()),
                ('experience_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('experience_author', models.CharField(default='No author', max_length=200)),
                ('experience_image', models.ImageField(default='notfound.jpg', upload_to='portfolio_logo')),
            ],
            options={
                'ordering': ['-experience_published'],
            },
        ),
    ]
