# Generated by Django 3.0.6 on 2020-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_author',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_summary',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_title',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_from',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_to',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_company',
            field=models.CharField(default='No company', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_job_title',
            field=models.CharField(default='No job title', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_section',
            field=models.CharField(choices=[('WORK EXPERIENCE', 'WORK EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('CERTIFICATION', 'CERTIFICATION'), ('COURSES', 'COURSES'), ('SIGNATURE SKILLS', 'SIGNATURE SKILLS'), ('PERSONAL SKILLS', 'PERSONAL SKILLS'), ('PROFESSIONAL SUMMARY', 'PROFESSIONAL SUMMARY')], default='No section', max_length=50),
        ),
    ]
