# Generated by Django 3.0.6 on 2020-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20200529_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-experience_order']},
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_order',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
