# Generated by Django 3.0.6 on 2020-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20200529_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['experience_order']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_image',
            field=models.ImageField(default='notfound.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_section',
            field=models.CharField(choices=[('', ''), ('WORK EXPERIENCE', 'WORK EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('CERTIFICATION', 'CERTIFICATION'), ('COURSES', 'COURSES'), ('SIGNATURE SKILLS', 'SIGNATURE SKILLS'), ('PERSONAL SKILLS', 'PERSONAL SKILLS'), ('PROFESSIONAL SUMMARY', 'PROFESSIONAL SUMMARY')], default='', max_length=50),
        ),
    ]
