# Generated by Django 3.0.6 on 2020-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20200529_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.CharField(blank=True, default='0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.CharField(blank=True, default='0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_image',
            field=models.ImageField(blank=True, default='notfound.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_job_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_order',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_section',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('WORK EXPERIENCE', 'WORK EXPERIENCE'), ('EDUCATION', 'EDUCATION'), ('CERTIFICATION', 'CERTIFICATION'), ('COURSES', 'COURSES'), ('SIGNATURE SKILLS', 'SIGNATURE SKILLS'), ('PERSONAL SKILLS', 'PERSONAL SKILLS'), ('PROFESSIONAL SUMMARY', 'PROFESSIONAL SUMMARY')], default=' ', max_length=50),
        ),
    ]
