# Generated by Django 3.0.6 on 2020-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_auto_20200529_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
