# Generated by Django 3.0.6 on 2020-05-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_auto_20200529_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_image',
        ),
    ]
